project_id = "rapduxzrdugvthezhcmk"

[functions.send-contact-email]
verify_jwt = false

[functions.notify-admin-event-created]
verify_jwt = false

[functions.handle-event-approval]
verify_jwt = false

[functions.send-approval-email]
verify_jwt = false

[functions.send-notification-emails]
verify_jwt = false

[functions.notify-subscribers-new-event]
verify_jwt = false

[functions.delete-user-account]
verify_jwt = false

[functions.import-tickster-events]
verify_jwt = false

[functions.gdpr-retention-check]
verify_jwt = false

[functions.gdpr-extend-retention]
verify_jwt = false
